#ifndef _ERROR_H_
#define _ERROR_H_

//todo zmenit
#define ERR_LEXICAL 200
#define ERR_SYNTAX 201
#define ERR_SEMANTIC_DEFINITION 3
#define ERR_SEMANTIC_TYPE 4
#define ERR_SEMANTIC_PARAMETERS_COUNT 5
#define ERR_SEMANTIC_OTHER 6
#define ERR_ZERO_DIVISION 9
#define ERR_INTERNAL 99

#endif
